export __CFLAGS=$CFLAGS;
export CFLAGS="$CFLAGS -isystem $CONDA_PREFIX/include"

export __CXXFLAGS=$CXXFLAGS
export CXXFLAGS="$CXXFLAGS -isystem $CONDA_PREFIX/include"

export __LD_LIBRARY_PATH=$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$CONDA_PREFIX/lib:$LD_LIBRARY_PATH

export __CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH
export CMAKE_PREFIX_PATH=$CONDA_PREFIX:$CMAKE_PREFIX_PATH

export DESTDIR=$CONDA_PREFIX

case "$OSTYPE" in
	darwin*)
		export __LDFLAGS=$LDFLAGS
		export LDFLAGS="$LDFLAGS -Wl,-rpath,$CONDA_PREFIX/lib -L$CONDA_PREFIX/lib"

		export __LDFLAGS_LD=$LDFLAGS_LD
		export LDFLAGS_LD="$LDFLAGS_LD -Wl,-rpath,$CONDA_PREFIX/lib -L$CONDA_PREFIX/lib"
		;;
	linux*)   
		export __LDFLAGS=$LDFLAGS
		export LDFLAGS="$LDFLAGS -Wl,-rpath,$CONDA_PREFIX/lib -Wl,-rpath-link,$CONDA_PREFIX/lib -L$CONDA_PREFIX/lib"
		;;
esac
