{% set version = "1.1.6" %}

package:
  name: oms
  version: {{ version }}

source:
  path: /Users/ivan/Seafile/devShared/oms

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - libprotobuf==3.6.1
    - zeromq==4.3.2
    - yaml-cpp
