# has issue: the generated PangolinConfig.cmake is incorrect
# PKGS_REQUIRED+=(glew eigen cmake)
# PKGS_RECOMMENDED+=(libjpeg libpng openexr libtiff ffmpeg lz4 zstd catch2)

# how to fix?
# remove:
# FILE(REMOVE "${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}Targets.cmake")
# export( TARGETS ${LIBRARY_NAME}
#         APPEND FILE "${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}Targets.cmake" )
# lib becomes: pangolin, zlib

{% set version = "0.8" %}

package:
  name: pangolin
  version: {{ version }}

source:
  url: https://github.com/stevenlovegrove/Pangolin/archive/refs/tags/v{{ version }}.tar.gz

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - glew
    - eigen
  run:
    - glew

about:
  home: https://github.com/stevenlovegrove/Pangolin
  license: MIT
  license_family: MIT
  license_file: LICENCE
  summary: Pangolin is a lightweight portable rapid development library for managing OpenGL display / interaction and abstracting video input.
  dev_url: https://github.com/stevenlovegrove/Pangolin
  doc_url: https://github.com/stevenlovegrove/Pangolin


